name: winser2019imageUpdate

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 15 * *'

permissions:
    id-token: write
    contents: write

jobs:
    winser2019imageUpdate:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Lint code
          run: |
            az bicep build --file ./products/winser2019image/main.bicep
        - name: Set up Azure CLI
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        - name: Get Azure VM Image
          id: get-image
          run: |
                image=$(az vm image list --offer WindowsServer --publisher MicrosoftWindowsServer --sku 2019-datacenter --all --query "[?sku=='2019-Datacenter'].version")
                imagelist=`echo $image | tr -d '[\r\n[],]'`
                imagedescription="@description(' $imagelist ')"
                sed -i -e "1s/^.*$/$imagedescription/g" ./products/winser2019image/main.bicep

        - name: Commit and push changes
          run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add ./products/winser2019image/main.bicep
                git commit -m "Update Bicep file with Azure VM image"
                git push
        - name: Deploy Template Spec
          run: |
                az ts create --name winser2019vm --location japaneast --resource-group templateSpecRG --version ${{ github.run_number }} --template-file ./products/winser2019image/main.bicep